name: over9000
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pip
  - nbdev
  - ipykernel
  - ipywidgets
  - jupyterlab_widgets
  - tqdm
# https://anaconda.org/pytorch/pytorch/files
  - pytorch=*=*cuda11.7* 
# https://anaconda.org/pytorch/torchvision/files
  - torchvision=0.14.*=*cu117*
##############################################################################################################################
  - tokenizers<0.13
  - psycopg2
  - SQLAlchemy
  - pandas
  - Pillow
  - fastapi
  - uvicorn
  - transformers
  - scrapy
  - dateparser
  - matplotlib
  - ftfy
  - dash
  - sentencepiece
  - docker-compose
  - gunicorn
  - cython
  - statsmodels
  - absl-py
  - future
  - comm
  - pytorch-lightning
  - scikit-learn 
  - timm
  - wandb
  - tabulate
  - colorama
  - rich
  - pip:
    - truegrad
    - fastai
