name: over9000
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - python
  - pip
  - ipywidgets
  - pytorch>=1.8.1
  - future
  - torchvision 
  - cudatoolkit=11.1
  - absl-py
  - statsmodels
  - pip:
    - wandb
    - pytorch-lightning>=0.10
    - tabulate
    - colorama
    - scikit-learn 
    #pip install fastprogress fastcore fastai"==2.2.7" --no-dependencies